import type { Metadata } from "next";

import { Montserrat } from "next/font/google";
import "./globals.css";
import { montserrat } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} text-white mt-3 bg-black antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
