import type { Metadata } from "next";

import "./globals.css";
import { montserrat } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}  mt-3 bg-[#121212] text-[#F5F5F5] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
