import type { Metadata } from "next";

import "./globals.css";
import { montserrat } from "./fonts";
import LogOut from "./ui/components/Button/LogOut";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}  min-h-screen bg-[var(--mainBg-color)] text-[var(--mainText-color)] antialiased`}
      >
        <LogOut />
        {children}
      </body>
    </html>
  );
}
